AllCops:
  TargetRubyVersion: 2.5.1
  Exclude:
    - bin/**
    - db/**/*
    - node_modules/**/*

Documentation:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Lint/Void:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 1500

MethodLength:
  Max: 25

BlockLength:
  Max: 70

